server:
  port: 2222

service:
  name: gateway
  version: 1.0

spring:
  application:
    name: ${service.name}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres


